# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_pronta.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 920)
        MainWindow.setStyleSheet("background: rgb(28, 33, 31)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 20, 411, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border-radius: 5px; /* Valor menor para menos arredondamento */\n"
"    background: #424d49 \n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(800, 20, 41, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("2.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 70, 1421, 16))
        self.line.setStyleSheet("QFrame[frameShape=\"4\"] { /* 4 é o valor de QFrame::HLine */\n"
"    border-top: 2px solid #2f3734; /* Ajuste a espessura e a cor conforme necessário */\n"
"    border-bottom: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    background-color: transparent; /* Isso evita que a cor de fundo cubra a borda superior */\n"
"}\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(20, 130, 1041, 741))
        self.openGLWidget.setObjectName("openGLWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 880, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 880, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 880, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(880, 880, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"        color: #898a81;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(210, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(390, 80, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(390, 100, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(600, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(600, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(810, 80, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(810, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_15.setObjectName("label_15")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1070, 130, 361, 20))
        self.line_2.setStyleSheet("QFrame[frameShape=\"4\"] { /* 4 é o valor de QFrame::HLine */\n"
"    border-top: 2px solid #2f3734; /* Ajuste a espessura e a cor conforme necessário */\n"
"    border-bottom: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    background-color: transparent; /* Isso evita que a cor de fundo cubra a borda superior */\n"
"}\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1070, 80, 61, 39))
        self.label_16.setMinimumSize(QtCore.QSize(0, 39))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_16.setObjectName("label_16")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(1130, 90, 41, 21))
        self.line_3.setStyleSheet("QFrame {\n"
"    border: none; /* Isso remove todas as bordas pré-existentes */\n"
"    border-left: 2px solid white; /* Isso aplica uma borda sólida branca apenas no lado esquerdo */\n"
"}\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(1140, 80, 91, 41))
        self.label_17.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"        color: #898a81;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1070, 140, 81, 21))
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1070, 290, 171, 31))
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1070, 430, 61, 31))
        self.label_20.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1070, 600, 121, 31))
        self.label_21.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1070, 756, 41, 31))
        self.label_22.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(1070, 470, 101, 21))
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_23.setObjectName("label_23")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(1080, 500, 331, 21))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #262626; /* Cor da borda da trilha */\n"
"    height: 4px; /* Altura da trilha ainda mais reduzida */\n"
"    background: #333333; /* Cor de fundo da trilha */\n"
"    margin: 0px 10px; /* Ajustar margens laterais para a alça alcançar as extremidades */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #bde5d5; /* Cor de fundo da alça */\n"
"\n"
"    width: 20px; /* Largura da alça */\n"
"    height: 20px; /* Altura da alça */\n"
"    border-radius: 10px; /* Arredondamento da borda da alça para manter a forma circular */\n"
"    margin-top: -8px; /* Margem superior ajustada */\n"
"    margin-bottom: -8px; /* Margem inferior ajustada */\n"
"    position: absolute; /* Posicionamento absoluto para ajustes precisos */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #bde5d5; /* Cor da parte preenchida da trilha à esquerda da alça */\n"
"    border-radius: 2px; /* Borda arredondada da parte preenchida */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #555555; /* Cor da parte não preenchida da trilha à direita da alça */\n"
"    border-radius: 2px; /* Borda arredondada da parte não preenchida */\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(1080, 570, 331, 21))
        self.horizontalSlider_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #262626; /* Cor da borda da trilha */\n"
"    height: 4px; /* Altura da trilha ainda mais reduzida */\n"
"    background: #333333; /* Cor de fundo da trilha */\n"
"    margin: 0px 10px; /* Ajustar margens laterais para a alça alcançar as extremidades */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #bde5d5; /* Cor de fundo da alça */\n"
"\n"
"    width: 20px; /* Largura da alça */\n"
"    height: 20px; /* Altura da alça */\n"
"    border-radius: 10px; /* Arredondamento da borda da alça para manter a forma circular */\n"
"    margin-top: -8px; /* Margem superior ajustada */\n"
"    margin-bottom: -8px; /* Margem inferior ajustada */\n"
"    position: absolute; /* Posicionamento absoluto para ajustes precisos */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #bde5d5; /* Cor da parte preenchida da trilha à esquerda da alça */\n"
"    border-radius: 2px; /* Borda arredondada da parte preenchida */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: #555555; /* Cor da parte não preenchida da trilha à direita da alça */\n"
"    border-radius: 2px; /* Borda arredondada da parte não preenchida */\n"
"}\n"
"")
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(1070, 540, 131, 21))
        self.label_24.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("Captura de tela 2024-03-25 130337.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 20, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/toggle-right.svg"))
        self.label.setObjectName("label")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(220, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("QLabel {\n"
"        color: #898a81;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(920, 20, 31, 31))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("../../Downloads/corner-up-right (1).svg"))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(970, 20, 31, 31))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("../../Downloads/download-cloud.svg"))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(1020, 20, 31, 31))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("../../Downloads/database.svg"))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1070, 20, 31, 31))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("../../Downloads/printer.svg"))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(1120, 20, 31, 31))
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("../../Downloads/message-circle.svg"))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(1170, 20, 31, 31))
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap("../../Downloads/folder.svg"))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(1220, 20, 31, 31))
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("../../Downloads/settings.svg"))
        self.label_33.setObjectName("label_33")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1270, 15, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 5px 15px;\n"
"    border: 2px solid white;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.2); /* Branco com transparência */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.4); /* Branco com mais transparência */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1070, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1190, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1310, 170, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1190, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1310, 220, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(1070, 330, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(1250, 330, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(1070, 380, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(1090, 642, 81, 21))
        self.label_34.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(1270, 705, 51, 21))
        self.label_35.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(1120, 724, 51, 21))
        self.label_36.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(1250, 653, 71, 21))
        self.label_37.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(1120, 685, 51, 21))
        self.label_38.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("    QLabel {\n"
"        color: #FFFFFF;\n"
"        padding: 4px;\n"
"    }\n"
"\n"
"")
        self.label_38.setObjectName("label_38")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(1170, 680, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(1170, 640, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(1170, 720, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(1320, 650, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(1320, 700, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(1080, 794, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(1260, 794, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: #090b0a; /* Fundo preto */\n"
"    color: white; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424d49; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #97b8ab; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(1080, 866, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: #a1c3b5; /* Fundo preto */\n"
"    color: black; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #97b8ab; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #88a599; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #88a599; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #97b8ab; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(1260, 866, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Satoshi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: #d04646; /* Fundo preto */\n"
"    color: black; /* Texto branco */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"\n"
"\n"
"    border: 2px solid #2f3734; /* Borda cinza */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #bf4040; /* Fundo cinza escuro para o estado hover */\n"
"    border: 2px solid #bf4040; /* Borda cinza clara para o estado hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d04646; /* Fundo mais escuro no estado pressed */\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "CHEST_PAT000-002"))
        self.label_4.setText(_translate("MainWindow", "Scale: 0.42"))
        self.label_5.setText(_translate("MainWindow", "W: 3008 | L: 2987"))
        self.label_6.setText(_translate("MainWindow", "Tech ID: 237 (Ville Norlund)"))
        self.label_7.setText(_translate("MainWindow", "ID: PAT0002851"))
        self.label_8.setText(_translate("MainWindow", "Pixel value: 97x"))
        self.label_9.setText(_translate("MainWindow", "Sum: 99xy"))
        self.label_10.setText(_translate("MainWindow", "Acq. Date: 12/07/2022"))
        self.label_11.setText(_translate("MainWindow", "Acq. Time: 09:34:37 AM"))
        self.label_12.setText(_translate("MainWindow", "Exp. Index: 2090"))
        self.label_13.setText(_translate("MainWindow", "STD: FFU67"))
        self.label_14.setText(_translate("MainWindow", "Min: 125xx"))
        self.label_15.setText(_translate("MainWindow", "Max: 255xx"))
        self.label_16.setText(_translate("MainWindow", "Tools"))
        self.label_17.setText(_translate("MainWindow", "Graphics"))
        self.label_18.setText(_translate("MainWindow", "Controls"))
        self.label_19.setText(_translate("MainWindow", "Image quality settings"))
        self.label_20.setText(_translate("MainWindow", "Filters"))
        self.label_21.setText(_translate("MainWindow", "Recontruction"))
        self.label_22.setText(_translate("MainWindow", "Run"))
        self.label_23.setText(_translate("MainWindow", "Reduce Noise"))
        self.label_24.setText(_translate("MainWindow", "Improve sharpness"))
        self.label_26.setText(_translate("MainWindow", "Anonymous mode"))
        self.pushButton.setText(_translate("MainWindow", "New Image"))
        self.pushButton_2.setText(_translate("MainWindow", "open"))
        self.pushButton_3.setText(_translate("MainWindow", "rotate"))
        self.pushButton_4.setText(_translate("MainWindow", "colormaps"))
        self.pushButton_5.setText(_translate("MainWindow", "clear"))
        self.pushButton_6.setText(_translate("MainWindow", "histogram"))
        self.pushButton_7.setText(_translate("MainWindow", "apply fat field"))
        self.pushButton_8.setText(_translate("MainWindow", "ROI 1"))
        self.pushButton_9.setText(_translate("MainWindow", "ROI 2"))
        self.pushButton_10.setText(_translate("MainWindow", "CALCULATE CNR - SNR"))
        self.label_34.setText(_translate("MainWindow", "projections"))
        self.label_35.setText(_translate("MainWindow", "dim X"))
        self.label_36.setText(_translate("MainWindow", "slices"))
        self.label_37.setText(_translate("MainWindow", "pixel size"))
        self.label_38.setText(_translate("MainWindow", "dim Y"))
        self.pushButton_12.setText(_translate("MainWindow", "0.45"))
        self.pushButton_13.setText(_translate("MainWindow", "0.45"))
        self.pushButton_14.setText(_translate("MainWindow", "0.45"))
        self.pushButton_15.setText(_translate("MainWindow", "0.45"))
        self.pushButton_16.setText(_translate("MainWindow", "0.45"))
        self.pushButton_11.setText(_translate("MainWindow", "run with CPU"))
        self.pushButton_17.setText(_translate("MainWindow", "run with GPU"))
        self.pushButton_18.setText(_translate("MainWindow", "save image"))
        self.pushButton_19.setText(_translate("MainWindow", "run with CPU"))
# import hapi logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
